networks:
   icloudpd:
      name: icloudpd
      driver: bridge
      ipam:
         driver: default
      driver_opts:
         com.docker.network.bridge.name: icloudpd

volumes:
   icloudpd_user1_config:
      name: icloudpd_user1_config
   icloudpd_user2_config:
      name: icloudpd_user2_config

services:
   icloudpd_user1:
      hostname: icloudpd_user1
      networks:
         icloudpd:
            aliases:
               - icloudpd_user1
      environment:
         - TZ=Europe/London
         - user=user1
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - icloudpd_user1_config:/config
         - ./iCloud/:/home/user1/iCloud/
   icloudpd_user2:
      hostname: icloudpd_user2
      networks:
         icloudpd:
            aliases:
               - icloudpd_user2
      environment:
         - TZ=Europe/London
         - user=user2
      image: boredazfcuk/icloudpd
      healthcheck:
         test: /usr/local/bin/healthcheck.sh
         start_period: 30s
      restart: always
      volumes:
         - icloudpd_user2_config:/config
         - ./iCloud/:/home/user2/iCloud/